version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  twilio-check-verify:
    lang: python3-http
    handler: ./twilio_check_verify
    secrets:
      - twilio-account-sid
      - twilio-auth-token
    labels:
      com.openfaas.scale.zero: false
    environment:
      twilio_check_verify_endpoint: https://verify.twilio.com/v2/Services/<YOUR_VERIFY_SERVICE_ID>/VerificationCheck
      twilio_account_sid_path: /var/openfaas/secrets/twilio-account-sid
      twilio_auth_token_path: /var/openfaas/secrets/twilio-auth-token
